# fly.toml app configuration file generated for mapdocs-frosty-water-3324 on 2024-03-05T05:37:24Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mapdocs'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '80'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
